### ISSUE TITLE
Crash TTT

### ISSUE THREAD

**Issue by dok441** [mcNuggets1/mg_ttt_anticrash#1]
Hello, your addon helps, but not perfectly, would still the case, that corpse is beginning to fly, that leads to crash. Can you do anything else in this case?

**Comment by mcNuggets1** [comment]
ttt_ragdoll_collide must be set to 1.

**Comment by dok441** [comment]
It doesn't help, all the same there are server crash.

**Comment by mcNuggets1** [comment]
Maybe an addon is creating a ragdoll incorrectly.
But my addon is fixing normal TTT crashing.

**Comment by dok441** [comment]
Means you are right. Some skins can influence or only some add-ons?

**Comment by dok441** [comment]
Если он умирает от админской команды "slay", то пишет в чат, что он будто убил кого-то и выдал себя, хотя он просто умер

**Comment by mcNuggets1** [comment]
...
Obviously Addons

**Comment by dok441** [comment]
[00:50] I'm so fucking happy [невиновный] kills Володар дверей [Хитман]. Оружие explosion.
Here you spoke, ideally works, and as a result the ravine pokazvat that after the death of the person from explosion of a barrel, probably the corpse has begun to fly and krashnut the server.
